version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: isp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isp_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: isp_phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-db

volumes:
  mysql_data: